version: "3.3"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  add-sub:
    image: "alvinwilta/add-sub"
    container_name: "add-sub"
    environment:
      - SERVER_HOSTNAME=localhost
      - SERVER_PORT=30
    ports:
      - "3000:30"
    command: npm start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.add-sub.entrypoints=web"
      - "traefik.http.routers.add-sub.rule=Path(`/whoami`)||Path(`/add`)||Path(`/sub`)"

  mult-div:
    image: "alvinwilta/mult-div"
    container_name: "mult-div"
    environment:
      - hostname=localhost
      - port=31
    ports:
      - "3001:31"
    command: npm start    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mult-div.entrypoints=web"
      - "traefik.http.routers.mult-div.rule=Path(`/`)||Path(`/mult`)||Path(`/div`)"
    