http:
  routers:
    whoamiRouter:
      rule: Path(`/whoami`)
      service: whoamibackend
    allbackendRouter:
      rule: PathPrefix(`/`)
      service: allbackend
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
          - url: "http://localhost:8010"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "3s"
    whoamibackend:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "3s"