http:
  routers:
    allbackendRouter:
      rule: Path(`/`)
      service: allbackend
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
          - url: "http://localhost:8010"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "3s"